
title: DEBTANU GANGULY
author: GitHub User
email: debtanu.july22@g,ail.com
description: > Hello there! I am Debtanu , a tech enthusiast.

# social links
twitter_username: your-twitter-handle
github_username:  debtanuganguly

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
